# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e81e0e886305f1f05d51e2e4abc881d397c239ebba58b09de46d8974457491aa3ea48dbfe1623e531c0241e65c5ac36dc2e904461a7f417547cb90528d62870

test:
  secret_key_base: dd1e2bfdf4fe780300970b00d9385333dd3e66ad0d26e2b02db65fbe6a12cc12960106d4e2d852b238d83ac944844884b37c414e61f36b18a3f18f7f7b898008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
